# Generated by Django 3.2.5 on 2021-07-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('A', 'Anime'), ('P', 'Programação'), ('S', 'Série'), ('E', 'Empreendedorismo'), ('F', 'Finanças')], default='P', max_length=1)),
            ],
        ),
    ]
