# Generated by Django 3.2.5 on 2021-07-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0003_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
