# Generated by Django 3.2.5 on 2021-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0007_alter_categoria_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(choices=[('ENT', 'Entrepreneurship'), ('FIN', 'Finances'), ('GAM', 'Games'), ('HEA', 'healthy'), ('MOV', 'Movies'), ('NER', 'Nerd'), ('PRO', 'Programming'), ('SER', 'Series'), ('TEC', 'Technology'), ('TRI', 'Trips')], default='P', max_length=3),
        ),
    ]
