# Generated by Django 3.2.5 on 2021-08-02 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0008_alter_categoria_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(choices=[('FRE', 'Free'), ('ENT', 'Entrepreneurship'), ('FIN', 'Finances'), ('GAM', 'Games'), ('HEA', 'healthy'), ('MOV', 'Movies'), ('NER', 'Nerd'), ('PRO', 'Programming'), ('TEC', 'Technology'), ('TRI', 'Trips')], default='FRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streamflix.categoria'),
        ),
    ]
