# Generated by Django 3.2.5 on 2021-08-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0009_auto_20210802_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default='FRE', on_delete=django.db.models.deletion.CASCADE, to='streamflix.categoria'),
        ),
    ]
