# Generated by Django 3.2.5 on 2021-08-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamflix', '0011_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='streamflix', to=settings.AUTH_USER_MODEL),
        ),
    ]
