# Generated by Django 3.2.5 on 2021-08-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streamflix', '0012_video_ower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ower',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamflix', to=settings.AUTH_USER_MODEL),
        ),
    ]
