# Generated by Django 3.2.5 on 2021-08-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamflix', '0013_alter_video_ower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ower',
        ),
    ]
